disabled_rules:
  - type_name
  - identifier_name
  - todo
  - nesting
  - vertical_whitespace
  - trailing_whitespace
  - function_body_length

included:
  - VVExtensions
  - VVExtensionsTests

line_length: 200

cyclomatic_complexity: 50

type_body_length:
  - 300
  - 400
